apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: eu-east-1

managednodeGroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    spot: true